name: Deploy

on:
  push:
    branches:
      - qa

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Environment Variables
        id: env
        run: |
          if [ ${{ github.ref }} = 'refs/heads/dev' ]; then
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          elif [ ${{ github.ref }} = 'refs/heads/qa' ]; then
            echo "ENVIRONMENT=qa" >> $GITHUB_ENV
          elif [ ${{ github.ref }} = 'refs/heads/prod' ]; then
            echo "ENVIRONMENT=prod" >> $GITHUB_ENV
          else
            echo "::error::Unsupported branch for deployment"
            exit 1
          fi

      - name: Deploy to ${{ steps.env.outputs.ENVIRONMENT }}
        run: |
          echo "Deploying to ${{ steps.env.outputs.ENVIRONMENT }} environment..."
          # Add your deployment script/commands here
