name: Deploy matrix

on:
  push:
    branches:
      - qa
      - dev
      - prod

jobs:
  deploy:
    if: contains('refs/heads/dev refs/heads/qa refs/heads/prod, github.ref')
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, qa, prod]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Environment Variables
        id: env
        run: |
          if [ "${{ matrix.environment }}" = 'dev' ]; then
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          elif [ "${{ matrix.environment }}" = 'qa' ]; then
            echo "ENVIRONMENT=qa" >> $GITHUB_ENV
          elif [ "${{ matrix.environment }}" = 'prod' ]; then
            echo "ENVIRONMENT=prod" >> $GITHUB_ENV
          else
            echo "::error::Unsupported environment for deployment"
            exit 1
          fi

      - name: Deploy to ${{ matrix.environment }}
        run: |
          echo "Deploying to ${{ matrix.environment }} environment..."
          # Add your deployment script/commands here
