name: automation in based on branches
on: 
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Specify the environment'
        required: false
        default: 'dev'
  push: 
    branches:
      - dev
      - qa
      - prod

env:
  AZURE_WEBAPP_NAME: azrwbapp
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  Build: 
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: folder stru
        run: | 
             pwd 
             ls -lrth
      
  Deploy: 
    needs: Build
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/dev' && 'dev' ||
                github.ref == 'refs/heads/qa' && 'qa' ||
                github.ref == 'refs/heads/prod' && 'prod' || 'dev' }}
    steps: 
      - uses: actions/checkout@v2
      - name: set environment variable
        run: |
          echo "ENV_CODE=dev" >> $GITHUB_ENV
          if [ "${{ github.ref }}" = "refs/heads/qa" ]; 
          then echo "ENV_CODE=qa" >> $GITHUB_ENV; 
          fi
          if [ "${{ github.ref }}" = "refs/heads/prod" ];
           then echo "ENV_CODE=prod" >> $GITHUB_ENV; 
           fi
      # - name: set environment variable
      #   run: echo "ENV_CODE=${{ github.ref == 'refs/heads/qa' && 'qa' || github.ref == 'refs/heads/prod' && 'prod' || 'dev' }}" >> $GITHUB_ENV

      - name: print env variable
        run: echo ${{ vars.DUMMY }}

      - name: test variable
        run: echo $ENV_CODE

      - name: list files 
        run: | 
          pwd 
          ls -a 
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
          
      - name: Restore
        run: dotnet restore ./CurrentTimeService.sln
        
      - name: Build
        run: dotnet build ./CurrentTimeService.sln --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./CurrentTimeService.sln --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
        
      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
          

  
