name: automation in based on branches
on: 
  workflow_dispatch:
    push: 
      branches:
        - dev
        - qa
        
jobs:
  Build: 
    name: build
    runs-on: ubuntu-latest

    environment: 
      name: ${{ github.ref == 'refs/heads/dev' && 'dev' || 'qa' }}

    steps:
      - uses: actions/checkout@v2
      - name: print env
        run: echo ${{ github.ref == 'refs/heads/dev' && 'dev' || 'qa' }}

      - name: folder stru
        run: | 
           pwd 
           ls 

  
