name: Deploy

on:
  push:
    branches:
      - dev
      - qa
      - prod 

jobs:
  deploy_dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Dev
        if: |
          contains(github.ref, 'Inox-Scale') || contains(github.ref, 'Inox-Scale-qualif') || contains(github.ref, 'Inox-Scale-prod')
        env:
          ENVIRONMENT: ${{ matrix.environment }}
        strategy:
          matrix:
            environment: [dev, qa, prod]
          exclude:
            - environment: dev
              if: contains(github.ref, 'Inox-Scale')
            - environment: qa
              if: contains(github.ref, 'Inox-Scale-qualif')
            - environment: prod
              if: contains(github.ref, 'Inox-Scale-prod')

        run: |
          echo "Deploying to $ENVIRONMENT environment..."
          # Add deployment steps for each environment
