name: Deploy appservice

on:
  push:
    branches:
      - dev
      - qa
      - prod

jobs:
  webapp-build:
    runs-on: ubuntu-latest
    name: Build Application

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

  webapp-deploy:
    runs-on: ubuntu-latest
    needs: webapp-build
    strategy:
      matrix:
        environment: [dev, qa, prod]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy to ${{ matrix.environment }}
        if: ${{ contains(github.ref == refs/heads/dev' || 'dev' || 
                 contains(github.ref == refs/heads/qa' || 'qa' || 
                 contains(github.ref == refs/heads/prod' || 'prod' }}
        run: |
          echo "Deploying to ${{ matrix.environment }} environment..."
          # Add deployment steps for each environment
