name: Deploy-app-service

on:
  push:
    branches:
      - dev
      - qa
      - prod

jobs:
  deploy:
    # if: 
      # contains('refs/heads/dev refs/heads/qa refs/heads/prod, github.ref')

    name: Deploy to ${{ matrix.environment }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, qa, prod]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to ${{ matrix.environment }}
        run: |
          if [ "${{ refs/heads/devt }}" == "dev" ]; then
            echo "Deploying to dev environment..."
            # Add deployment steps for dev environment
          elif [ "${{ refs/heads/qa }}" == "qa" ]; then
            echo "Deploying to qa environment..."
            # Add deployment steps for qa environment
          elif [ "${{ refs/heads/prod }}" == "prod" ]; then
            echo "Deploying to prod environment..."
            # Add deployment steps for prod environment
          else
            echo "Unsupported environment"
            exit 1
          fi
      - name: folder
        run: | 
          ls -a 
          pwd