name: Node.js Build

on:
  push:
    branches:
      - 'dev'
      - 'qa'
      - 'prod'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: ['dev', 'qa', 'prod']

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build for ${{ matrix.environment }}
        if: github.ref == 'refs/heads/'${{ matrix.environment }}
        run: npm run build:${{ matrix.environment }}
