name: Deploy-app

on:
  push:
    branches:
      - dev
      - qa
      - prod 

jobs:
  deploy_dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Dev
        if: |
          contains('refs/heads/dev, refs/heads/qa  refs/heads/prod', github.ref)
        env:
          ENVIRONMENT: ${{ matrix.environment }}
        strategy:
          matrix:
            environment: [dev, qa, prod]
          exclude:
            - environment: dev
              if: contains(github.ref, 'dev')
            - environment: qa
              if: contains(github.ref, 'qa')
            - environment: prod
              if: contains(github.ref, 'prod')

        run: |
          echo "Deploying to $ENVIRONMENT environment..."
          # Add deployment steps for each environment
