name: Repository events
on: 
  workflow_dispatch:
    inputs:
      string: 
        description: A string input
        type: string
        required: true
        default: "Default value"
    

jobs: 
  checkout-test: 
    runs-on: ubuntu-latest
    steps: 
      - run: 
          echo $GITHUB_SHA
          echo $GITHUB_REF
          echo ${{ inputs.string }}

      - uses: actions/checkout@v3
  
