name: Repository events
on: 
  workflow_dispatch:
    

jobs: 
  checkout-test: 
    runs-on: ubuntu-latest
    steps: 
      - run: 
          echo $GITHUB_SHA
          echo $GITHUB_REF

      - uses: actions/checkout@v3
  
