name: System Matrix Pipeline

on:
  push:
    branches:
      - dev
      - qa
      - prod

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, qa, prod]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Environment
      run: echo "Environment: ${{ matrix.environment }}"

    - name: Build and Test
      run: pwd
        # Add your build and test commands here

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: |
      github.event_name == 'push' &&
      (
        (matrix.environment == 'dev' && github.ref == 'refs/heads/dev') ||
        (matrix.environment == 'qa' && github.ref == 'refs/heads/qa') ||
        (matrix.environment == 'prod' && github.ref == 'refs/heads/prod')
      )
    strategy:
      matrix:
        environment: [dev, qa, prod]

    steps:
    - name: Deploy to Environment
      run: pwd
        # Add your deployment commands here for each environment

