name: workflow_dispatch test
on:
  workflow_dispatch:
    inputs:
      environment: 
        description: run main
        type: environment
        required: true
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - run: 
        echo $GITHUB_SHA
        echo $GITHUB_REF
    - run: |
        echo "string: ${{ inputs.string }}"
        ls