name: Repository eve
on:
  push:
    branches:
      - dev
      - qa
      - prod

jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Dev Environment
        run: ./deploy.sh dev 
      - run: 
          echo $GITHUB_SHA
          echo $GITHUB_REF

  deploy_qa:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/qa'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to QA Environment
        run: ./deploy.sh qa
      - run: 
          echo $GITHUB_SHA
          echo $GITHUB_REF
          ls

  deploy_prod:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/prod'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Prod Environment
        run: ./deploy.sh prod
      - run: 
          echo $GITHUB_SHA
          echo $GITHUB_REF

    
