name: Repository events

on: 
  workflow_dispatch:
  push: 
    branches:
      - main
      - qa 
      - dev
    
jobs: 
  checkout-test: 
    runs-on: ubuntu-latest
    steps: 
      - run: 
          echo $GITHUB_SHA
          echo $GITHUB_REF
      - run: |
          echo "string: ${{ inputs.string }}"
          ls

      - uses: actions/checkout@v3
  Deploy: 
    if: 
        contains('refs/heads/dev refs/heads/qa refs/heads/main, githhub.ref')
    runs-on: ubuntu-latest
    name: deploy
    strategy:
      matrix: 
        environment: [dev, qa, main]
        exclude: 
          - environment: ${{ github.ref == 'refs/heads/dev' || 'dev' }}
          - environment: ${{ github.ref == 'refs/heads/qa' || 'qa' }}
          - environment: ${{ github.ref == 'refs/heads/main' || 'prod' }}
    environment: ${{ matrix.environment }}
  
