name: System Matrix Pipeline

on:
  push:
    branches:
      - dev
      - qa
      - prod

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, qa, prod]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Environment
      run: echo "Environment: ${{ matrix.environment }}"

    - name: Build and Test
      run: pwd
        # Add your build and test commands here

  deploy:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        environment: [dev, qa, prod]

    steps:
    - name: Deploy to Environment
      if: github.event_name == 'push' && github.ref == 'refs/heads/${{ matrix.environment }}'
      run: pwd
        # Add your deployment commands here for each environment
